### ISSUE TITLE
Terminal theming

### ISSUE THREAD

**Issue by DHedgecock** [DHedgecock/radical-vscode#14]
Terminal theming needs a once-over to make sure the black and white colors work with the background. Afterwards update the iterm version.

**Comment by toti1212** [comment]
+1

**Comment by DHedgecock** [comment]
Latest update has new terminal colors. I've spent a TON of time trying to find a good set. I think there's still some minor work to do, but the update feels _much_ closer to radical.

If you have feedback I'd love to hear it: https://github.com/DHedgecock/radical-vscode/issues/16
