### ISSUE TITLE
Extension not found on marketplace

### ISSUE THREAD

**Issue by Bounteous17** [DHedgecock/radical-vscode#27]
Executing this order in the marketplace extensions search engine does not find any results:
```
ext install dhedgecock.radical-vscode
```
How to simulate:
```
Version: 1.56.2
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-14T00:17:59.109Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Linux x64 5.10.33-gentoo-dist
```

**Comment by DHedgecock** [comment]
Hello, thanks for opening this ticket.

I haven't managed extensions with the command line before, and couldn't find documentation on `ext`. I did find these docs for Command line extensions management (https://code.visualstudio.com/docs/editor/extension-marketplace#_command-line-extension-management)

From that doc, running `code --install-extension dhedgecock.radical-vscode` succeeded.

**Comment by AlexDraeger** [comment]
Hello,

run into the same problem and your solution didn't worked for me, cause the package/extension still can't be found.
Downloading the Resource from MS Marketplace and then run the following command finally worked.

`code --install-extension <local_vsix_file_path>`

Maybe this will help some people.

Cheers and thanks for this Theme :)
